name: causal

dependencies:
    - python==3.6.7
    - pip:
        - numpy==1.25.2
        - gym==0.26.2
        - matplotlib==3.1.3
        - opencv-python
        - ray==2.6.3
        - tensorflow==2.13.0
        - setproctitle
        - psutil
        - lz4
        - boto3==1.4.8
        - redis==3.3.2
        - pytz

